FROM node AS build

WORKDIR /application/frontend

ADD scripts /scripts
ADD ./application/frontend ./

COPY /application/frontend/package*.json ./

RUN chmod +x /scripts/appown.sh && \
    bash /scripts/appown.sh && \
    npm install

ADD ./application/frontend ./

RUN npm run build

USER appown

FROM nginx:alpine
RUN apk update && apk add gettext
COPY --from=build /application/frontend/build /usr/share/nginx/html
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./application/frontend/frontend-nginx.conf.template /etc/nginx/conf.d/frontend-nginx.conf.template
CMD ["/bin/sh", "-c", "envsubst '$API_URL_GCP' < /etc/nginx/conf.d/frontend-nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
