FROM python:3.12.2-slim

ADD scripts /scripts
RUN sed -i 's/\r$//' /scripts/appown.sh
ADD ./application/api /app/api

RUN chmod +x /scripts/appown.sh && \
    bash /scripts/appown.sh && \
    pip install -r /app/api/requirements.txt

WORKDIR /app/api
USER appown
CMD ["python", "main.py"]