version: '3'
services:
  app:
    build: .
    command: python main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGODB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local


