apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: {{ .Values.api.image }}:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - name: api
      port: {{ .Values.api.port }}
      nodePort: {{ .Values.api.nodePort }}
  type: {{ .Values.api.serviceType }}