apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongo.name }}
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name }}
    spec:
      containers:
        - name: {{ .Values.mongo.name }}
          image: {{ .Values.mongo.image }}:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-secret
                  key: MONGO_PASSWORD
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.pvcName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      nodePort: {{ .Values.mongo.nodePort }}
  type: {{ .Values.mongo.serviceType }}