apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.name }}-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MONGO_HOST: {{ .Values.mongo.host | toString | b64enc }}
  MONGO_USER: {{ .Values.mongo.user | toString | b64enc }}
  MONGO_PASSWORD: {{ .Values.mongo.password | toString | b64enc }}
  MONGO_AUTH_SOURCE: {{ .Values.mongo.authSource | toString | b64enc }}