global:
  namespace: dev
  imagetag: latest
  imagepullpolicy: IfNotPresent

api:
  name: api
  serviceName: api-service
  replicas: 2
  image: api
  port: 8000
  serviceType: NodePort
  nodePort: 30333

frontend:
  name: frontend
  serviceName: frontend-service
  replicas: 2
  image: frontend
  port: 3000
  serviceType: ClusterIP

mongo:
  name: mongo
  serviceName: mongo-service
  replicas: 1
  image: mongo
  port: 27017
  serviceType: NodePort
  nodePort: 30332
  storage:
    size: 2Gi
    className: standard
  credentials:
    username: YWRtaW4=
    password: cGFzc3dvcmQ=
    host: bW9uZ28tc2VydmljZQ==
    authSource: YWRtaW4=

ingress:
  enabled: true
  host: localhost
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
