apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER

            - name: MONGO_PORT
              value: "27017"

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD

            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key:  MONGO_HOST

            - name: MONGO_AUTH_SOURCE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_AUTH_SOURCE
          ports:
            - containerPort: 27017
              name: mongo

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

--- #Service

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: dev
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      nodePort: 30332
  type: NodePort
