apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: dev
type: Opaque
data:
  MONGO_HOST: bW9uZ28tc2VydmljZQ==
  MONGO_USER: YWRtaW4=
  MONGO_PASSWORD: cGFzc3dvcmQ=
  MONGO_AUTH_SOURCE: YWRtaW4=