pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build API image'){
            steps{
                script {
                    def apiImage = docker.build("api:latest", "-f ../Dockerfile-backend .")
                }
            }
        }
    }
}