name: GCP Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: environment

      destroy_infrastructure:
        description: 'Destroy infrastructure'
        required: true
        type: boolean
        default: false
        

jobs:
  create_infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'

    defaults:
      run:
        working-directory: ./Terraform

    if: ${{github.event.inputs.destroy_infrastructure == 'false' }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Auth to GCP
        uses: google-github-actions/auth@v2 
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Save Infrastructure Info to GH Vars
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          API_SERVICE_NAME=$(terraform output -raw api_service_name)
          gh variable set API_SERVICE_NAME --body "$API_SERVICE_NAME" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}
          
          API_AR_URL=$(terraform output -raw api_ar)
          gh variable set API_AR_URL --body "$API_AR_URL" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}
          
          API_URL=$(terraform output -raw api_url)
          gh variable set API_URL --body "$API_URL" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}
          
          FRONTEND_SERVICE_NAME=$(terraform output -raw frontend_service_name)
          gh variable set FRONTEND_SERVICE_NAME --body "$FRONTEND_SERVICE_NAME" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}

          FRONTEND_URL=$(terraform output -raw frontend_url)
          gh variable set FRONTEND_URL --body "$FRONTEND_URL" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}
          
          FRONTEND_AR_URL=$(terraform output -raw frontend_ar)
          gh variable set FRONTEND_AR_URL --body "$FRONTEND_AR_URL" --repo ${{ github.repository }} --env ${{ github.event.inputs.environment }}
            
          

  destroy_infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'

    defaults:
      run:
        working-directory: ./Terraform

    if: ${{ github.event.inputs.destroy_infrastructure == 'true' }} 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Auth to GCP
        uses: google-github-actions/auth@v2 
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
    
    
