name: CI Pipeline

on:
  push:
    branches:
      - ci
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build API Docker Image
        run: |
          docker build -t api:latest -f Dockerfile-backend .

      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend:latest -f Dockerfile-frontend .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/flashcards-app:api-latest
            ${{ env.REGISTRY }}/flashcards-app:frontend-latest
          build-args: |
            API_IMAGE=api:latest
            FRONTEND_IMAGE=frontend:latest





