name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      API-version:
        description: 'Version of API image e.g. v1.0'
        required: true
        type: string
    
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Image
        run: docker build -t api:${{inputs.API-version}} -f Dockerfile-backend .

      - name: Run API Tests
        run: docker run --rm api:${{inputs.API-version}} /bin/bash -c "pytest  -v"

      - name: Push API Image to Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-backend
          push: true
          tags: ghcr.io/outron/api:${{inputs.API-version}}
              






