name: CI Pipeline

on:
  push:
    branches:
      - ci
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build API Docker Image
        run: |
          docker build -t api:latest -f Dockerfile-backend .

      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend:latest -f Dockerfile-frontend .





