name: CI/CD Flashcards

on:
  workflow_dispatch:
    inputs:
      deploy-api:
        description: 'Build, test and deploy API service'
        required: true
        type: boolean
        
      deploy-frontend:
        description: 'Build, test and deploy Frontend service'
        required: true
        type: boolean
        
      api-version:
        description: 'Version of API image e.g. 1.0'
        required: true
        type: string
        
      frontend-version:
        description: 'Version of Frontend image e.g. 1.0'
        required: true
        type: string
        
      environment:
        description: 'Deployment environment'
        required: true
        type: environment

jobs:
  build_test_push_api:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-api == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API Image
        run: docker build -t api:${{inputs.API-version}} -f Dockerfile-backend .

      - name: Run API Tests
        run: docker run --rm api:${{inputs.API-version}} /bin/bash -c "pytest  -v"

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: Push API Image to Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-backend
          push: true
          tags: ${{ vars.API_AR }}/api:${{inputs.API-version}}
