name: CI/CD Flashcards

on:
  workflow_dispatch:
    inputs:
      deploy-api:
        description: 'Build, test and deploy API service'
        required: true
        type: boolean

      deploy-frontend:
        description: 'Build, test and deploy Frontend service'
        required: true
        type: boolean

      api-version:
        description: 'Version of API image e.g. 1.0'
        required: true
        type: string

      frontend-version:
        description: 'Version of Frontend image e.g. 1.0'
        required: true
        type: string

      environment:
        description: 'Deployment environment'
        required: true
        type: environment

jobs:
  build_test_push_api:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'
    if: ${{ github.event.inputs.deploy-api == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}
          token_format: 'access_token'

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{steps.auth.outputs.access_token}}

      - name: Build API Image
        run: docker build -t api:${{github.event.inputs.API-version}} -f Dockerfile-backend .

      - name: Run API Tests
        run: docker run --rm api:${{github.event.inputs.API-version}} /bin/bash -c "pytest  -v"

      - name: Push API Image to Registry
        run: |
          AR_TAG=${{vars.API_AR_URL}}/api:${{github.event.inputs.api-version}}
          docker tag api:${{github.event.inputs.api-version}} $AR_TAG
          docker push $AR_TAG

    outputs:
      api-image_url: ${{ vars.API_AR_URL }}/api:${{ github.event.inputs.api-version }}

  deploy_api:
    runs-on: ubuntu-latest
    needs: build_test_push_api
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'
    if: ${{ github.event.inputs.deploy-api == 'true' }}

    steps:
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Deploy API image to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.API_SERVICE_NAME }}
          image: ${{ needs.build_test_push_api.outputs.api-image_url }}
          region: ${{ vars.GCP_REGION }}
          env_vars: |
            ENVIRONMENT=${{ github.event.inputs.environment }}
            MONGO_URI=${{ secrets.MONGO_URI }}