name: CI Pipeline

on:
  push:
    branches:
      - ci
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build API Docker Image
        run: |
          docker build -t api:latest -f Dockerfile-backend .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-backend
          push: true
          tags: ghcr.io/outron/flashcards-app-api:latest







